### ISSUE TITLE
I can't transilitirate, I get an error

### ISSUE THREAD

**Issue by slkh** [owo/camel_tools#3]
This is the command the and error message that I get:
camel_transliterate --scheme bw2ar ../large_file.txt
Error: An **unkown** error **occured** during transliteration.

- File tested on is attached.
- Spelling errors in error message (bolded)
[large_file.txt](https://github.com/owo/camel_tools/files/1601332/large_file.txt)

**Comment by owo** [comment]
Closing this issue since no problem could be found.
